export const GET_ATRICLES_REQUEST = 'GET_ATRICLES_REQUEST';
export const GET_ATRICLES_SUCCESS = 'GET_ATRICLES_SUCCESS';
export const GET_ATRICLES_FAILURE = 'GET_ATRICLES_FAILURE';
export const GET_ADDITIONAL_ARTICLES_BUNDLE = 'GET_ADDITIONAL_ARTICLES_BUNDLE';
